# TACHE 5 : Symmetry

Dans ce notebook nous allons étudier l’effet de 3 éléments de symétrie différents, chacun pour 1 atome différent du cristal SrCN₂.

Dans cette cellule de code, nous récupérons la structure conventionnelle du SrCN₂ depuis Materials Project.
Dans ce notebook, nous utiliserons la maille conventionnelle car elle offre une meilleure visualisation des opérations de symétrie par rapport à la maille primitive. Cela permet une interprétation plus claire et intuitive des éléments de symétrie du cristal.

In [21]:
import numpy as np
from mp_api.client import MPRester
from pymatgen.core.operations import SymmOp
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from jupyter_jsmol.pymatgen import quick_view
from plotly.subplots import make_subplots
import plotly.graph_objects as go
from jupyter_jsmol import JsmolView
from ipywidgets import Layout, widgets, interact

In [22]:
mp_key = "hGFJONMWFhZMzX55ulNNTvmOkGE07nJS"
mp_id = "mp-12317"

In [23]:
with MPRester(mp_key) as m:
    prim_struc = m.get_structure_by_material_id(mp_id)
conv_struc = SpacegroupAnalyzer(prim_struc).get_conventional_standard_structure()
symmops = SpacegroupAnalyzer(conv_struc).get_space_group_operations()

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

In [24]:
JsmolView.default_info['color']='white'
view = quick_view(prim_struc, "packed", conventional = True)
display(view)

JsmolView(layout=Layout(align_self='stretch', height='400px'))

## Première opération de symétrie : 

La première opération de symétrie que nous allons analyser est une rotation d'ordre 4 appliquée à l'atome Sr.

In [25]:
i_atom = 1 #Sr
i_symmop = 3 #'-y, x-y, z'

In [26]:
symmop = symmops[i_symmop - 1]
print(symmop)

Rot:
[[ 0. -1.  0.]
 [ 1. -1.  0.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.]


In [40]:
pos_init = conv_struc.sites[i_atom -1].frac_coords
print('Coordonnées initiales du Sr :',pos_init)
pos_final = symmop.operate(pos_init)
print('Coordonnées finales du Sr :', pos_final)

Coordonnées initiales du Sr : [1.  1.  0.5]
Coordonnées finales du Sr : [-1.  -1.  -0.5]


In [29]:
v1 = quick_view(conv_struc)
display(v1)
v1.script("draw symop 3 {atomno=1}")

JsmolView(layout=Layout(align_self='stretch', height='400px'))

### Analyse :
La rotation autour d'un axe est une opération de première espèce. Cette opération conserve la chiralité. Le déterminant de la matrice de rotation vaut 1.

$$
\begin{bmatrix} 0 & -1 & 0 \\ 1 & -1 & 0 \\ 0 & 0 & 1 \end{bmatrix} \times \begin{bmatrix} x \\ y \\ z \end{bmatrix} = \begin{bmatrix} -y \\ x-y \\ z \end{bmatrix}
$$

## Deuxième opération de symétrie :

La seconde opération de symétrie que nous allons analysé est une réflexion appliquée à l'atome C.

In [30]:
i_atom = 2 #C
i_symmop = 12 # 'x, x-y, z'

In [31]:
symmop = symmops[i_symmop - 1] 
print(symmop)

Rot:
[[ 1.  0.  0.]
 [ 1. -1.  0.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.]


In [39]:
pos_init = conv_struc.sites[i_atom -1].frac_coords
print('Coordonnées initiales du C:',pos_init)
pos_final = symmop.operate(pos_init)
print('Coordonnées finales du C:',pos_final)

Coordonnées initiales du C: [1.  1.  0.5]
Coordonnées finales du C: [-1.  -1.  -0.5]


In [34]:
v1 = quick_view(conv_struc)
display(v1)
v1.script("draw symop 12 {atomno=2}")

JsmolView(layout=Layout(align_self='stretch', height='400px'))

### Analyse :
La réflexion par rapport à un plan miroir est une opération de deuxième espèce. Le déterminant de la matrice vaut -1.
$$
\begin{bmatrix} 1 & 0 & 0 \\ 1 & -1 & 0 \\ 0 & 0 & 1 \end{bmatrix} \times \begin{bmatrix} x \\ y \\ z \end{bmatrix} = \begin{bmatrix} x \\ x-y \\ z \end{bmatrix}
$$

## Troisième opération de symétrie :

La troisième opération de symétrie que nous allons analyser est une inversion appliquée à l'atome N.

In [35]:
i_atom =3 #N
i_symmop = 2 #'-x, -y, -z'

In [36]:
symmop = symmops[i_symmop - 1]
print(symmop)

Rot:
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.]


In [37]:
pos_init = conv_struc.sites[i_atom -1].frac_coords
print('Coordonnées initiales du N:',pos_init)
pos_final = symmop.operate(pos_init)
print('Coordonnées finales du N:',pos_final)

Coordonnées initiales du N: [1.  1.  0.5]
Coordonnées finales du N: [-1.  -1.  -0.5]


In [38]:
v1 = quick_view(conv_struc)
display(v1)
v1.script("draw symop 2 {atomno=3}")

JsmolView(layout=Layout(align_self='stretch', height='400px'))

### Analyse
L'inversion par rapport à un centre est une opération de deuxième espèce. Le déterminant de la matrice vaut -1.
$$
\begin{bmatrix} -1 & 0 & 0 \\ 0 & -1 & 0 \\ 0 & 0 & -1 \end{bmatrix} \times \begin{bmatrix} x \\ y \\ z \end{bmatrix} = \begin{bmatrix} -x \\ -y \\ -z \end{bmatrix}
$$